import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function Layout({ children }) {
  console.log('children: ', children)
  return (
    <div className={styles.container}>
      {/* 공통으로 사용하는 Head를 Layout으로 사용 */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 공통으로 사용하는 Head와 Footer 사이에 우리가 만든 페이지를 출력한다. */}
      <main className={styles.main}>{children}</main>

      {/* 공통으로 사용하는 footer Layout으로 사용 */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
